# Generated by Django 5.0.4 on 2024-05-03 05:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, null=True, verbose_name='Slug')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='Image')),
                ('location', models.CharField(max_length=255, null=True, verbose_name='Location')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Review', 'Review'), ('Rejected', 'Rejected')], default='Published', max_length=15, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news-list',
            },
        ),
    ]
