# Generated by Django 5.0.4 on 2024-05-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blcTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=500, null=True, verbose_name='Course')),
                ('full_name', models.CharField(max_length=500, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=500, null=True, verbose_name='Email')),
                ('address', models.CharField(max_length=500, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=500, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=500, null=True, verbose_name='State')),
                ('country', models.CharField(max_length=500, null=True, verbose_name='Country')),
                ('postalcode', models.CharField(max_length=500, null=True, verbose_name='Postal Code')),
                ('price', models.IntegerField(null=True, verbose_name='Price')),
                ('contact', models.CharField(max_length=500, null=True, verbose_name='Contact')),
                ('information', models.CharField(max_length=500, null=True, verbose_name='Information')),
                ('token', models.TextField(null=True, verbose_name='Token No')),
                ('enrolled_date', models.DateTimeField(auto_now=True, verbose_name='Start Date')),
            ],
            options={
                'verbose_name': 'BLC Transaction',
                'verbose_name_plural': 'BLC Transaction',
                'db_table': 'payment_blc_transaction',
            },
        ),
        migrations.CreateModel(
            name='cttTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=500, null=True, verbose_name='Email')),
                ('address', models.CharField(max_length=500, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=500, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=500, null=True, verbose_name='State')),
                ('country', models.CharField(max_length=500, null=True, verbose_name='Country')),
                ('postalcode', models.CharField(max_length=500, null=True, verbose_name='Postal Code')),
                ('price', models.IntegerField(null=True, verbose_name='Price')),
                ('contact', models.CharField(max_length=500, null=True, verbose_name='Contact')),
                ('information', models.CharField(max_length=500, null=True, verbose_name='Information')),
                ('token', models.TextField(null=True, verbose_name='Token No')),
                ('enrolled_date', models.DateTimeField(auto_now=True, verbose_name='Start Date')),
            ],
            options={
                'verbose_name': 'Teacher Training Transaction',
                'verbose_name_plural': 'Teacher Training Transaction',
                'db_table': 'payment_ctt_transaction',
            },
        ),
        migrations.CreateModel(
            name='indTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=500, null=True, verbose_name='Email')),
                ('price', models.IntegerField(null=True, verbose_name='Price')),
                ('contact', models.CharField(max_length=500, null=True, verbose_name='Contact')),
                ('token', models.TextField(null=True, verbose_name='Token No')),
                ('instamojo_response', models.TextField(blank=True, null=True, verbose_name='Instamojo Response')),
                ('enrolled_date', models.DateTimeField(auto_now=True, verbose_name='Start Date')),
            ],
            options={
                'verbose_name': 'India Training Transaction',
                'verbose_name_plural': 'India Training Transaction',
                'db_table': 'payment_ind_transaction',
            },
        ),
        migrations.CreateModel(
            name='ly2Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=500, null=True, verbose_name='Course')),
                ('full_name', models.CharField(max_length=500, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=500, null=True, verbose_name='Email')),
                ('address', models.CharField(max_length=500, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=500, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=500, null=True, verbose_name='State')),
                ('country', models.CharField(max_length=500, null=True, verbose_name='Country')),
                ('postalcode', models.CharField(max_length=500, null=True, verbose_name='Postal Code')),
                ('price', models.CharField(max_length=100, null=True, verbose_name='Price')),
                ('contact', models.CharField(max_length=500, null=True, verbose_name='Contact')),
                ('information', models.CharField(max_length=500, null=True, verbose_name='Information')),
                ('token', models.TextField(null=True, verbose_name='Token No')),
                ('enrolled_date', models.DateTimeField(auto_now=True, verbose_name='Start Date')),
            ],
            options={
                'verbose_name': 'LY2 Transaction',
                'verbose_name_plural': 'LY2 Transaction',
                'db_table': 'payment_ly2_transaction',
            },
        ),
        migrations.CreateModel(
            name='prozoneTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=500, null=True, verbose_name='Email')),
                ('membership_name', models.CharField(max_length=500, null=True, verbose_name='Membership Name')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiry Date')),
                ('address', models.CharField(max_length=500, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=500, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=500, null=True, verbose_name='State')),
                ('country', models.CharField(max_length=500, null=True, verbose_name='Country')),
                ('postalcode', models.CharField(max_length=500, null=True, verbose_name='Postal Code')),
                ('price', models.CharField(max_length=100, null=True, verbose_name='Price')),
                ('contact', models.CharField(max_length=500, null=True, verbose_name='Contact')),
                ('token', models.TextField(null=True, verbose_name='Token No')),
                ('subscribed_date', models.DateTimeField(auto_now=True, verbose_name='Start Date')),
            ],
            options={
                'verbose_name': 'Prozone Transaction',
                'verbose_name_plural': 'Prozone Transaction',
                'db_table': 'payment_prozone_transaction',
            },
        ),
        migrations.CreateModel(
            name='wcTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=500, null=True, verbose_name='Email')),
                ('address', models.CharField(max_length=500, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=500, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=500, null=True, verbose_name='State')),
                ('country', models.CharField(max_length=500, null=True, verbose_name='Country')),
                ('postalcode', models.CharField(max_length=500, null=True, verbose_name='Postal Code')),
                ('price', models.CharField(max_length=100, null=True, verbose_name='Price')),
                ('contact', models.CharField(max_length=500, null=True, verbose_name='Contact')),
                ('information', models.CharField(max_length=500, null=True, verbose_name='Information')),
                ('token', models.TextField(null=True, verbose_name='Token No')),
                ('enrolled_date', models.DateTimeField(auto_now=True, verbose_name='Start Date')),
            ],
            options={
                'verbose_name': 'World Conference Transaction',
                'verbose_name_plural': 'World Conference Transaction',
                'db_table': 'payment_world_conference',
            },
        ),
    ]
