# Generated by Django 5.0.4 on 2024-05-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Contact', 'Contact'), ('LY2', 'LY2'), ('Basic Learning Course', 'Basic Learning Course'), ('Leader Training', 'Leader Training'), ('Teacher Training', 'Teacher Training'), ('School', 'School'), ('Business', 'Business'), ('Special Needs', 'Special Needs'), ('Profile Enquiry', 'Profile Enquiry')], max_length=100, null=True, verbose_name='Category')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Full Name')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=15, null=True, verbose_name='Contact')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('message', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
                'db_table': 'report-contact-lists',
            },
        ),
        migrations.CreateModel(
            name='InfoBooklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Full Name')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('downloaded', models.DateTimeField(auto_now=True, verbose_name='Download Date')),
            ],
            options={
                'verbose_name': 'Info Booklet',
                'verbose_name_plural': 'Info Booklet',
                'db_table': 'report-info-booklet',
            },
        ),
        migrations.CreateModel(
            name='LYTourEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name='Full Name')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=15, null=True, verbose_name='Contact')),
                ('category', models.CharField(default='Jaipur', max_length=20, null=True, verbose_name='Category')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'LY Tour Enquiry',
                'verbose_name_plural': 'LY Tour Enquiry',
                'db_table': 'report-ly-tour-enquiry',
            },
        ),
        migrations.CreateModel(
            name='SpiritualRetreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=255, null=True, verbose_name='Retreat Month')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Full Name')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('whatsapp', models.CharField(max_length=15, null=True, verbose_name='Contact')),
                ('location', models.CharField(max_length=255, null=True, verbose_name='Location')),
                ('info', models.TextField(null=True, verbose_name='Information')),
                ('accommodation', models.TextField(null=True, verbose_name='Accommodation')),
                ('comments', models.TextField(null=True, verbose_name='Comments')),
                ('token', models.TextField(null=True, verbose_name='Token')),
                ('whatsapp_status', models.BooleanField(default=False, null=True, verbose_name='WhatsApp Status')),
                ('email_status', models.BooleanField(default=False, null=True, verbose_name='Email Status')),
                ('submitted_date', models.DateTimeField(auto_now=True, verbose_name='Submitted Date')),
            ],
            options={
                'verbose_name': 'Spiritual Retreat',
                'verbose_name_plural': 'Spiritual Retreat',
                'db_table': 'report-spiritual-retreat-registration',
            },
        ),
        migrations.CreateModel(
            name='TrainerProfileEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Full Name')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=15, null=True, verbose_name='Contact')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('message', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Trainer Profile Enquiry',
                'verbose_name_plural': 'Trainer Profile Enquiry',
                'db_table': 'report-trainer-profile-enquiry',
            },
        ),
        migrations.CreateModel(
            name='ZoomLCEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name='Full Name')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=15, null=True, verbose_name='Contact')),
                ('occupation', models.CharField(max_length=255, null=True, verbose_name='Occupation')),
                ('country', models.CharField(max_length=15, null=True, verbose_name='Country')),
                ('token', models.CharField(max_length=100, null=True, verbose_name='Token')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Zoom LC Enquiry',
                'verbose_name_plural': 'Zoom LC Enquiry',
                'db_table': 'report-zoom-lc-enquiry',
            },
        ),
    ]
