# Generated by Django 5.0.4 on 2024-05-03 05:50

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prozone/article/%Y/%m/%d/', verbose_name='Image')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=15, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': "DrK's Pro Diary",
                'verbose_name_plural': "DrK's Pro Diary",
                'db_table': 'prozone-drk-diary-list',
            },
        ),
        migrations.CreateModel(
            name='ProDownloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, null=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='prozone/download/resource/%Y/%m/%d/', verbose_name='Image')),
                ('download_link', models.FileField(null=True, upload_to='', verbose_name='Upload File')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=15, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Pro Resource',
                'verbose_name_plural': 'Pro Resources',
                'db_table': 'prozone-resource-list',
            },
        ),
        migrations.CreateModel(
            name='ProPhotosCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=15, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Photos Category',
                'verbose_name_plural': 'Photos Category',
                'db_table': 'prozone-photos-category-list',
            },
        ),
        migrations.CreateModel(
            name='ProQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, unique=True, verbose_name='Title')),
                ('slug', models.CharField(max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='prozone/download/quotes/%Y/%m/%d', verbose_name='Image')),
                ('download_link', models.FileField(null=True, upload_to='', verbose_name='Upload File')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=15, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'prozone-quotes-list',
            },
        ),
        migrations.CreateModel(
            name='ProResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prozone/research/%Y/%m/%d/', verbose_name='Image')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=15, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Research Article',
                'verbose_name_plural': 'Research Articles',
                'db_table': 'prozone-research-list',
            },
        ),
        migrations.CreateModel(
            name='ProVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Description')),
                ('video_code', models.CharField(max_length=500, unique=True, verbose_name='Video Code')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=15, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Pro Video',
                'verbose_name_plural': 'Pro Videos',
                'db_table': 'prozone-videos-list',
            },
        ),
        migrations.CreateModel(
            name='ProPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='prozone/download/photos/%Y/%m/%d/', verbose_name='Image')),
                ('download_link', models.FileField(null=True, upload_to='', verbose_name='Upload File')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=15, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prozone.prophotoscat')),
            ],
            options={
                'verbose_name': 'Photos',
                'verbose_name_plural': 'Photos',
                'db_table': 'prozone-download-photos-list',
            },
        ),
    ]
