# Generated by Django 5.0.4 on 2024-05-03 05:50

import ckeditor_uploader.fields
import django.db.models.deletion
import embed_video.fields
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'club-category',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('email', models.EmailField(max_length=200, verbose_name='Contact Email')),
                ('frequency', models.CharField(max_length=200, verbose_name='Meeting Frequency')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('contact_name', models.CharField(max_length=200, null=True, verbose_name='Contact Person')),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='club/%Y/%m/%d/', verbose_name='Club Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='club/%Y/%m/%d/', verbose_name='Club Image 2')),
                ('video1', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Club Video 1')),
                ('video2', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Club Video 2')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.country')),
                ('state', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.state')),
                ('category_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubcategory')),
            ],
            options={
                'verbose_name': 'Laughter Club',
                'verbose_name_plural': 'Laughter Clubs',
                'db_table': 'laughter_club',
            },
        ),
    ]
