# Generated by Django 5.0.4 on 2024-05-03 05:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Self Token Number')),
                ('parent_token', models.CharField(max_length=100, null=True, verbose_name='Parent Token Number')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Token',
                'verbose_name_plural': 'Account Tokens',
                'db_table': 'tokens-account',
            },
        ),
        migrations.CreateModel(
            name='LeaderUniqueToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('count', models.IntegerField(default=0, verbose_name='Registration Count')),
                ('token', models.UUIDField(default=uuid.uuid4, verbose_name='Self Token Number')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leader Registration',
                'verbose_name_plural': 'Leader Registration',
                'db_table': 'tokens-leader-registration',
            },
        ),
        migrations.CreateModel(
            name='TeacherUniqueToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('count', models.IntegerField(default=0, verbose_name='Registration Count')),
                ('token', models.UUIDField(default=uuid.uuid4, verbose_name='Self Token Number')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Registration',
                'verbose_name_plural': 'Teacher Registration',
                'db_table': 'tokens-teacher-registration',
            },
        ),
    ]
